### ISSUE TITLE
 Specification mandates value for attribute crossorigin, line 16, column 76

### ISSUE THREAD

**Issue by bms1223s** [whitews/FlowKit#128]
I tried to import the wsp file in [https://github.com/SofieVG/FlowSOM/tree/master/inst/extdata]
but I have the error

`Traceback (most recent call last):

  File "/Users/secret/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/var/folders/y5/64wd3k_9257d1d89c_h7fbc80000gq/T/ipykernel_1830/4272598072.py", line 1, in <module>
    fks_fj.import_flowjo_workspace(wsp_path)

  File "/Users/secret/opt/anaconda3/lib/python3.9/site-packages/flowkit/_models/session.py", line 231, in import_flowjo_workspace
    wsp_sample_groups = wsp_utils.parse_wsp(workspace_file_or_path, ignore_transforms=ignore_transforms)

  File "/Users/secret/opt/anaconda3/lib/python3.9/site-packages/flowkit/_utils/wsp_utils.py", line 483, in parse_wsp
    doc_type, root_xml, gating_ns, data_type_ns, transform_ns = _get_xml_type(workspace_file_or_path)

  File "/Users/secret/opt/anaconda3/lib/python3.9/site-packages/flowkit/_utils/xml_utils.py", line 127, in _get_xml_type
    xml_document = etree.parse(xml_file_or_path)

  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse

  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument

  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL

  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile

  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile

  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError

  File "/Users/secret/Downloads/SampleFlowData/gating.wsp", line 16
    <link rel="preconnect" href="https://github.githubassets.com/" crossorigin>
                                                                            ^
XMLSyntaxError: Specification mandates value for attribute crossorigin, line 16, column 76`

**Comment by whitews** [comment]
Hi,

I cloned the FlowSOM repo and the wsp file parses without error for me in FlowKit 0.9.3. Googling the error, I think you may have downloaded the file from a browser and it downloaded as some kind of HTML instead of the original XML.

**Comment by bms1223s** [comment]
yes
