### ISSUE TITLE
Cannot Install flowkit

### ISSUE THREAD

**Issue by gernophil** [whitews/FlowKit#171]
Hey everyone,

I am trying to install flowkit into an conda env using this yaml file:
```
name: flowkit
channels:
  - conda-forge
  - defaults

dependencies:
  - pip
  - pip:
    - flowkit
```
However, if fails (I guess when installing flowutils) with this error. I get the same error with arm64 conda and x86_64 conda in rosetta2 mode. Any ideas how to solve this?
```
Failed to build flowutils

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/setup.py:16: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.Distribution().fetch_build_eggs(['numpy>=1.19'])
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/setup.py", line 16, in <module>
          dist.Distribution().fetch_build_eggs(['numpy>=1.19'])
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/dist.py", line 908, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/.eggs/numpy-1.25.2-py3.11-macosx-11.0-arm64.egg/numpy-1.25.2.dist-info' -> '/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/.eggs/numpy-1.25.2-py3.11-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flowutils
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/setup.py:16: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.Distribution().fetch_build_eggs(['numpy>=1.19'])
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/setup.py", line 16, in <module>
          dist.Distribution().fetch_build_eggs(['numpy>=1.19'])
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/dist.py", line 908, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/installer.py", line 106, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/gernophil/miniconda3/envs/flowkit/lib/python3.11/site-packages/setuptools/wheel.py", line 173, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/.eggs/numpy-1.25.2-py3.11-macosx-11.0-arm64.egg/numpy-1.25.2.dist-info' -> '/private/var/folders/ws/vdb_nvyj35g9ck_srpvqpccm0000gn/T/pip-install-zzdur3nd/flowutils_b97db8eb40274926b4c11e091efba988/.eggs/numpy-1.25.2-py3.11-macosx-11.0-arm64.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for flowutils
ERROR: Could not build wheels for flowutils, which is required to install pyproject.toml-based projects

failed
```

**Comment by whitews** [comment]
Hi,

Python 3.11 is not supported by the current version of FlowKit or FlowUtils. FlowUtils has pre-built wheels for 3.7 - 3.10, but requires a compiler to build from source. I hope to support 3.11 in the next version.

**Comment by gernophil** [comment]
Oh yes, sorry. Could have found this out myself 😅. Thanks a lot!
